### ISSUE TITLE
No place holder for edit user (neither first name or last)on user dashboard (edit user details)

### ISSUE THREAD

**Issue by Matt8728** [Derek229/vaccine-passport#48]
[
![Issue_1](https://user-images.githubusercontent.com/77548409/115912044-7863e780-a434-11eb-9c9e-e6c8f4d4a2d0.png)
](url)

**Comment by tvonhake** [comment]
When you complete registration for a new account it will prompt you in the browser to update your first and last name. Since there is no first and last name currently nothing will show in the form. We will add placeholders for first and last name to clear up confusion.
