### ISSUE TITLE
On "Required Vaccines list" 

### ISSUE THREAD

**Issue by Matt8728** [Derek229/vaccine-passport#51]
1. On "Required Vaccines List" when we tried to enter a vaccine thats not preset it will break the app. (we were logged in as a verifier.)

![Issue_4 1](https://user-images.githubusercontent.com/77548409/115913555-5f5c3600-a436-11eb-9007-095468f89cc8.png)

[.  ](url)

[
![Issue_4 2](https://user-images.githubusercontent.com/77548409/115913650-80bd2200-a436-11eb-96fc-aca6cfeda912.png)
](url)

**Comment by maxmanayan** [comment]
Steps to Reproduce:

- In Verifier acct, type in a vaccine that is not in the db...
- Click 'Verify' and it will break the app
