### ISSUE TITLE
User Dashboard 

### ISSUE THREAD

**Issue by Matt8728** [Derek229/vaccine-passport#52]
As an issuer on "edit user Details" pop up "close" button doesn't cancel the edit function. So any unwanted changes you made will get saved even if you don't want them to. 

![Issue_5 1](https://user-images.githubusercontent.com/77548409/115915460-f88c4c00-a438-11eb-8fd4-2a6f5526eddf.png)

[
![Issue_5 2](https://user-images.githubusercontent.com/77548409/115915497-04780e00-a439-11eb-89e2-2a7e3a54ab6d.png)
](url)

![Issue_5 3](https://user-images.githubusercontent.com/77548409/115915551-15c11a80-a439-11eb-99cc-1023af09ec53.png)

**Comment by maxmanayan** [comment]
Steps to Reproduce: 
- Click 'Edit User Details'
- Edit names BUT click 'Close' 
- Edits are still submitted
